/**
 * GENERATED FILE — do not edit by hand.
 *
 * Regenerate with `npm run gen:countries` (see scripts/gen-countries.ts).
 * Country names are endonyms sourced from CLDR territory data, resolved to
 * each territory's most-populous official/de-facto-official language and
 * NEVER localised into the app's own UI language.
 */
import type { Region } from './region.ts';

export interface Country {
  readonly code: string;
  readonly name: string;
  readonly region: Region;
}

export const COUNTRIES: readonly Country[] = [
  { code: "AC", name: "Ascension Island", region: "OCE" },
  { code: "AD", name: "Andorra", region: "EU" },
  { code: "AE", name: "الإمارات العربية المتحدة", region: "MENA" },
  { code: "AF", name: "افغانستان", region: "APAC" },
  { code: "AG", name: "Antigua & Barbuda", region: "LATAM" },
  { code: "AI", name: "Anguilla", region: "LATAM" },
  { code: "AL", name: "Shqipëri", region: "EU" },
  { code: "AM", name: "Հայաստան", region: "APAC" },
  { code: "AO", name: "Angola", region: "EU" },
  { code: "AQ", name: "Antarctica", region: "OCE" },
  { code: "AR", name: "Argentina", region: "LATAM" },
  { code: "AS", name: "American Samoa", region: "OCE" },
  { code: "AT", name: "Österreich", region: "EU" },
  { code: "AU", name: "Australia", region: "OCE" },
  { code: "AW", name: "Aruba", region: "LATAM" },
  { code: "AX", name: "Åland", region: "EU" },
  { code: "AZ", name: "Azərbaycan", region: "APAC" },
  { code: "BA", name: "Bosna i Hercegovina", region: "EU" },
  { code: "BB", name: "Barbados", region: "LATAM" },
  { code: "BD", name: "বাংলাদেশ", region: "APAC" },
  { code: "BE", name: "België", region: "EU" },
  { code: "BF", name: "Burkina Faso", region: "EU" },
  { code: "BG", name: "България", region: "EU" },
  { code: "BH", name: "البحرين", region: "MENA" },
  { code: "BI", name: "Uburundi", region: "EU" },
  { code: "BJ", name: "Bénin", region: "EU" },
  { code: "BL", name: "Saint-Barthélemy", region: "LATAM" },
  { code: "BM", name: "Bermuda", region: "NA" },
  { code: "BN", name: "Brunei", region: "SEA" },
  { code: "BO", name: "Bolivia", region: "LATAM" },
  { code: "BQ", name: "Caribisch Nederland", region: "LATAM" },
  { code: "BR", name: "Brasil", region: "LATAM" },
  { code: "BS", name: "Bahamas", region: "LATAM" },
  { code: "BT", name: "འབྲུག", region: "APAC" },
  { code: "BV", name: "Bouvet Island", region: "LATAM" },
  { code: "BW", name: "Botswana", region: "EU" },
  { code: "BY", name: "Беларусь", region: "EU" },
  { code: "BZ", name: "Belize", region: "LATAM" },
  { code: "CA", name: "Canada", region: "NA" },
  { code: "CC", name: "Cocos (Keeling) Islands", region: "OCE" },
  { code: "CD", name: "Congo-Kinshasa", region: "EU" },
  { code: "CF", name: "République centrafricaine", region: "EU" },
  { code: "CG", name: "Congo-Brazzaville", region: "EU" },
  { code: "CH", name: "Schweiz", region: "EU" },
  { code: "CI", name: "Côte d’Ivoire", region: "EU" },
  { code: "CK", name: "Cook Islands", region: "OCE" },
  { code: "CL", name: "Chile", region: "LATAM" },
  { code: "CM", name: "Cameroun", region: "EU" },
  { code: "CN", name: "中国", region: "APAC" },
  { code: "CO", name: "Colombia", region: "LATAM" },
  { code: "CP", name: "Clipperton Island", region: "OCE" },
  { code: "CQ", name: "Sark", region: "EU" },
  { code: "CR", name: "Costa Rica", region: "LATAM" },
  { code: "CU", name: "Cuba", region: "LATAM" },
  { code: "CV", name: "Cabo Verde", region: "EU" },
  { code: "CW", name: "Kòrsou", region: "LATAM" },
  { code: "CX", name: "Christmas Island", region: "OCE" },
  { code: "CY", name: "Κύπρος", region: "APAC" },
  { code: "CZ", name: "Česko", region: "EU" },
  { code: "DE", name: "Deutschland", region: "EU" },
  { code: "DG", name: "Diego Garcia", region: "OCE" },
  { code: "DJ", name: "جيبوتي", region: "EU" },
  { code: "DK", name: "Danmark", region: "EU" },
  { code: "DM", name: "Dominica", region: "LATAM" },
  { code: "DO", name: "República Dominicana", region: "LATAM" },
  { code: "DZ", name: "الجزائر", region: "MENA" },
  { code: "EA", name: "Ceuta y Melilla", region: "EU" },
  { code: "EC", name: "Ecuador", region: "LATAM" },
  { code: "EE", name: "Eesti", region: "EU" },
  { code: "EG", name: "مصر", region: "MENA" },
  { code: "EH", name: "الصحراء الغربية", region: "MENA" },
  { code: "ER", name: "ኤርትራ", region: "EU" },
  { code: "ES", name: "España", region: "EU" },
  { code: "ET", name: "ኢትዮጵያ", region: "EU" },
  { code: "FI", name: "Suomi", region: "EU" },
  { code: "FJ", name: "Fiji", region: "OCE" },
  { code: "FK", name: "Falkland Islands", region: "LATAM" },
  { code: "FM", name: "Micronesia", region: "OCE" },
  { code: "FO", name: "Føroyar", region: "EU" },
  { code: "FR", name: "France", region: "EU" },
  { code: "GA", name: "Gabon", region: "EU" },
  { code: "GB", name: "United Kingdom", region: "EU" },
  { code: "GD", name: "Grenada", region: "LATAM" },
  { code: "GE", name: "საქართველო", region: "APAC" },
  { code: "GF", name: "Guyane française", region: "LATAM" },
  { code: "GG", name: "Guernsey", region: "EU" },
  { code: "GH", name: "Ghana", region: "EU" },
  { code: "GI", name: "Gibraltar", region: "EU" },
  { code: "GL", name: "Kalaallit Nunaat", region: "NA" },
  { code: "GM", name: "Gambia", region: "EU" },
  { code: "GN", name: "Guinée", region: "EU" },
  { code: "GP", name: "Guadeloupe", region: "LATAM" },
  { code: "GQ", name: "Guinea Ecuatorial", region: "EU" },
  { code: "GR", name: "Ελλάδα", region: "EU" },
  { code: "GS", name: "South Georgia & South Sandwich Islands", region: "LATAM" },
  { code: "GT", name: "Guatemala", region: "LATAM" },
  { code: "GU", name: "Guam", region: "OCE" },
  { code: "GW", name: "Guiné-Bissau", region: "EU" },
  { code: "GY", name: "Guyana", region: "LATAM" },
  { code: "HK", name: "中國香港特別行政區", region: "APAC" },
  { code: "HM", name: "Heard & McDonald Islands", region: "OCE" },
  { code: "HN", name: "Honduras", region: "LATAM" },
  { code: "HR", name: "Hrvatska", region: "EU" },
  { code: "HT", name: "Haiti", region: "LATAM" },
  { code: "HU", name: "Magyarország", region: "EU" },
  { code: "IC", name: "Canarias", region: "EU" },
  { code: "ID", name: "Indonesia", region: "SEA" },
  { code: "IE", name: "Ireland", region: "EU" },
  { code: "IL", name: "ישראל", region: "MENA" },
  { code: "IM", name: "Isle of Man", region: "EU" },
  { code: "IN", name: "भारत", region: "APAC" },
  { code: "IO", name: "British Indian Ocean Territory", region: "EU" },
  { code: "IQ", name: "العراق", region: "MENA" },
  { code: "IR", name: "ایران", region: "MENA" },
  { code: "IS", name: "Ísland", region: "EU" },
  { code: "IT", name: "Italia", region: "EU" },
  { code: "JE", name: "Jersey", region: "EU" },
  { code: "JM", name: "Jamaica", region: "LATAM" },
  { code: "JO", name: "الأردن", region: "MENA" },
  { code: "JP", name: "日本", region: "APAC" },
  { code: "KE", name: "Kenya", region: "EU" },
  { code: "KG", name: "Кыргызстан", region: "APAC" },
  { code: "KH", name: "កម្ពុជា", region: "SEA" },
  { code: "KI", name: "Kiribati", region: "OCE" },
  { code: "KM", name: "جزر القمر", region: "EU" },
  { code: "KN", name: "St. Kitts & Nevis", region: "LATAM" },
  { code: "KP", name: "북한", region: "APAC" },
  { code: "KR", name: "대한민국", region: "APAC" },
  { code: "KW", name: "الكويت", region: "MENA" },
  { code: "KY", name: "Cayman Islands", region: "LATAM" },
  { code: "KZ", name: "Казахстан", region: "APAC" },
  { code: "LA", name: "ລາວ", region: "SEA" },
  { code: "LB", name: "لبنان", region: "MENA" },
  { code: "LC", name: "St. Lucia", region: "LATAM" },
  { code: "LI", name: "Liechtenstein", region: "EU" },
  { code: "LK", name: "ශ්‍රී ලංකාව", region: "APAC" },
  { code: "LR", name: "Liberia", region: "EU" },
  { code: "LS", name: "Lesotho", region: "EU" },
  { code: "LT", name: "Lietuva", region: "EU" },
  { code: "LU", name: "Luxembourg", region: "EU" },
  { code: "LV", name: "Latvija", region: "EU" },
  { code: "LY", name: "ليبيا", region: "MENA" },
  { code: "MA", name: "المغرب", region: "MENA" },
  { code: "MC", name: "Monaco", region: "EU" },
  { code: "MD", name: "Republica Moldova", region: "EU" },
  { code: "ME", name: "Crna Gora", region: "EU" },
  { code: "MF", name: "Saint-Martin", region: "LATAM" },
  { code: "MG", name: "Madagasikara", region: "EU" },
  { code: "MH", name: "Marshall Islands", region: "OCE" },
  { code: "MK", name: "Северна Македонија", region: "EU" },
  { code: "ML", name: "Mali", region: "EU" },
  { code: "MM", name: "မြန်မာ", region: "SEA" },
  { code: "MN", name: "Монгол", region: "APAC" },
  { code: "MO", name: "中國澳門特別行政區", region: "APAC" },
  { code: "MP", name: "Northern Mariana Islands", region: "OCE" },
  { code: "MQ", name: "Martinique", region: "LATAM" },
  { code: "MR", name: "موريتانيا", region: "MENA" },
  { code: "MS", name: "Montserrat", region: "LATAM" },
  { code: "MT", name: "Malta", region: "EU" },
  { code: "MU", name: "Mauritius", region: "EU" },
  { code: "MV", name: "Maldives", region: "APAC" },
  { code: "MW", name: "Malawi", region: "EU" },
  { code: "MX", name: "México", region: "LATAM" },
  { code: "MY", name: "Malaysia", region: "SEA" },
  { code: "MZ", name: "Moçambique", region: "EU" },
  { code: "NA", name: "Namibia", region: "EU" },
  { code: "NC", name: "Nouvelle-Calédonie", region: "OCE" },
  { code: "NE", name: "Niger", region: "EU" },
  { code: "NF", name: "Norfolk Island", region: "OCE" },
  { code: "NG", name: "Nigeria", region: "EU" },
  { code: "NI", name: "Nicaragua", region: "LATAM" },
  { code: "NL", name: "Nederland", region: "EU" },
  { code: "NO", name: "Norge", region: "EU" },
  { code: "NP", name: "नेपाल", region: "APAC" },
  { code: "NR", name: "Nauru", region: "OCE" },
  { code: "NU", name: "Niue", region: "OCE" },
  { code: "NZ", name: "New Zealand", region: "OCE" },
  { code: "OM", name: "عُمان", region: "MENA" },
  { code: "PA", name: "Panamá", region: "LATAM" },
  { code: "PE", name: "Perú", region: "LATAM" },
  { code: "PF", name: "Polynésie française", region: "OCE" },
  { code: "PG", name: "Papua Niugini", region: "OCE" },
  { code: "PH", name: "Philippines", region: "SEA" },
  { code: "PK", name: "پاکستان", region: "APAC" },
  { code: "PL", name: "Polska", region: "EU" },
  { code: "PM", name: "Saint-Pierre-et-Miquelon", region: "NA" },
  { code: "PN", name: "Pitcairn Islands", region: "OCE" },
  { code: "PR", name: "Puerto Rico", region: "LATAM" },
  { code: "PS", name: "الأراضي الفلسطينية", region: "MENA" },
  { code: "PT", name: "Portugal", region: "EU" },
  { code: "PW", name: "Palau", region: "OCE" },
  { code: "PY", name: "Paraguay", region: "LATAM" },
  { code: "QA", name: "قطر", region: "MENA" },
  { code: "RE", name: "La Réunion", region: "EU" },
  { code: "RO", name: "România", region: "EU" },
  { code: "RS", name: "Србија", region: "EU" },
  { code: "RU", name: "Россия", region: "EU" },
  { code: "RW", name: "U Rwanda", region: "EU" },
  { code: "SA", name: "المملكة العربية السعودية", region: "MENA" },
  { code: "SB", name: "Solomon Islands", region: "OCE" },
  { code: "SC", name: "Seychelles", region: "EU" },
  { code: "SD", name: "السودان", region: "MENA" },
  { code: "SE", name: "Sverige", region: "EU" },
  { code: "SG", name: "Singapore", region: "SEA" },
  { code: "SH", name: "St. Helena", region: "EU" },
  { code: "SI", name: "Slovenija", region: "EU" },
  { code: "SJ", name: "Svalbard og Jan Mayen", region: "EU" },
  { code: "SK", name: "Slovensko", region: "EU" },
  { code: "SL", name: "Sierra Leone", region: "EU" },
  { code: "SM", name: "San Marino", region: "EU" },
  { code: "SN", name: "Senegaal", region: "EU" },
  { code: "SO", name: "Soomaaliya", region: "EU" },
  { code: "SR", name: "Suriname", region: "LATAM" },
  { code: "SS", name: "South Sudan", region: "EU" },
  { code: "ST", name: "São Tomé e Príncipe", region: "EU" },
  { code: "SV", name: "El Salvador", region: "LATAM" },
  { code: "SX", name: "Sint Maarten", region: "LATAM" },
  { code: "SY", name: "سوريا", region: "MENA" },
  { code: "SZ", name: "Eswatini", region: "EU" },
  { code: "TA", name: "Tristan da Cunha", region: "OCE" },
  { code: "TC", name: "Turks & Caicos Islands", region: "LATAM" },
  { code: "TD", name: "Tchad", region: "EU" },
  { code: "TF", name: "French Southern Territories", region: "EU" },
  { code: "TG", name: "Togo", region: "EU" },
  { code: "TH", name: "ไทย", region: "SEA" },
  { code: "TJ", name: "Тоҷикистон", region: "APAC" },
  { code: "TK", name: "Tokelau", region: "OCE" },
  { code: "TL", name: "Timor-Leste", region: "SEA" },
  { code: "TM", name: "Türkmenistan", region: "APAC" },
  { code: "TN", name: "تونس", region: "MENA" },
  { code: "TO", name: "Tonga", region: "OCE" },
  { code: "TR", name: "Türkiye", region: "MENA" },
  { code: "TT", name: "Trinidad & Tobago", region: "LATAM" },
  { code: "TV", name: "Tuvalu", region: "OCE" },
  { code: "TW", name: "台灣", region: "APAC" },
  { code: "TZ", name: "Tanzania", region: "EU" },
  { code: "UA", name: "Україна", region: "EU" },
  { code: "UG", name: "Uganda", region: "EU" },
  { code: "UM", name: "U.S. Outlying Islands", region: "OCE" },
  { code: "US", name: "United States", region: "NA" },
  { code: "UY", name: "Uruguay", region: "LATAM" },
  { code: "UZ", name: "Oʻzbekiston", region: "APAC" },
  { code: "VA", name: "Città del Vaticano", region: "EU" },
  { code: "VC", name: "St. Vincent & Grenadines", region: "LATAM" },
  { code: "VE", name: "Venezuela", region: "LATAM" },
  { code: "VG", name: "British Virgin Islands", region: "LATAM" },
  { code: "VI", name: "U.S. Virgin Islands", region: "LATAM" },
  { code: "VN", name: "Việt Nam", region: "SEA" },
  { code: "VU", name: "Vanuatu", region: "OCE" },
  { code: "WF", name: "Wallis-et-Futuna", region: "OCE" },
  { code: "WS", name: "Samoa", region: "OCE" },
  { code: "XK", name: "Kosovë", region: "EU" },
  { code: "YE", name: "اليمن", region: "MENA" },
  { code: "YT", name: "Mayotte", region: "EU" },
  { code: "ZA", name: "South Africa", region: "EU" },
  { code: "ZM", name: "Zambia", region: "EU" },
  { code: "ZW", name: "Zimbabwe", region: "EU" },
];

const BY_CODE: ReadonlyMap<string, Country> = new Map(COUNTRIES.map((c) => [c.code, c]));

export function countryByCode(code: string): Country | undefined {
  return BY_CODE.get(code);
}

export function isCountryCode(code: unknown): code is string {
  return typeof code === 'string' && BY_CODE.has(code);
}
