/** Onboarding'de önerilen varsayılan taban adlar. Spec §2.2. */
export const NICKNAME_POOL: readonly string[] = [
  'TurboKral',
  'ApexAvcısı',
  'PitStopUsta',
  'DriftBaron',
  'RedFlagRider',
  'ChequeredFlag',
  'SlipstreamKing',
  'GridHunter',
  'PolePositionX',
  'FastLapPro',
  'VelocityWolf',
  'RaceLineBey',
  'OverTakeMachine',
  'BoxBoxLegend',
  'HotLapHero',
  'CircuitGhost',
  'SafetyCarKral',
  'TurboNitro',
  'RaceCraftPro',
  'GripMaster',
  'DrsZone',
  'FinishLineX',
  'PaddockKing',
  'TarmacTiger',
  'CornerCutter',
  'FullThrottleX',
  'SpeedDemonTR',
  'LightsOutGo',
  'MidfieldWolf',
  'ChampionshipRun',
] as const;
